### ISSUE TITLE
TS & Jest mocks

### ISSUE THREAD

**Issue by embiem** [klzns/klzns.github.io#1]
Nice Blog!

I recently came across your blog as it was top google search result for `jest mockimplementation typescript`. Specifically this page: https://klzns.github.io/how-to-use-type-script-and-jest-mocks

This didn't work for me in current TS version, but this did work: https://github.com/kulshekhar/ts-jest/issues/576#issuecomment-458178545

Maybe you'd consider updating the post as it is first result in Google searches?

Cheers!

**Comment by klzns** [comment]
Hi @embiem, thanks for the feedback!

I've tested the solution proposed in my blog post and it seemed to work fine.

I tested in two ways:

## Using create-react-app with TS

I created a fresh install of create-react-app with TS running:
1. `yarn create react-app my-app --template typescript`
2. `yarn add @testing-library/react @testing-library/jest-dom`

And I created two examples:

1. [Example mocking a node module](https://github.com/klzns/sample-ts-react-app/blob/master/src/FoobarNodeModule.test.tsx)
2. [Example mocking a local module](https://github.com/klzns/sample-ts-react-app/blob/master/src/FoobarLocal.test.tsx)

That's the output of the tests:

![image](https://user-images.githubusercontent.com/284515/77242176-6339db00-6bda-11ea-8c5b-083245b299db.png)

In this test I used [TypeScript v3.7.5](https://github.com/klzns/sample-ts-react-app/blob/2d9e84e1823f12d3bf1d883430b1ae62ee551f81/yarn.lock#L10029).


## Using react-boilerplate-typescript

Since the first test worked fine, I thought the issue might be related to the usage of ts-jest.

So I also created a [branch](https://github.com/klzns/sample-ts-react-app/tree/react-boilerplate-typescript) using the [react-boilerplate-typescript](https://github.com/react-boilerplate/react-boilerplate-typescript) that someone mentioned in the thread.

With the same two examples:
1. [Example mocking a node module](https://github.com/klzns/sample-ts-react-app/blob/react-boilerplate-typescript/app/components/FoobarNodeModule/tests/index.test.tsx)
2. [Example mocking a local module](https://github.com/klzns/sample-ts-react-app/blob/react-boilerplate-typescript/app/components/FoobarLocal/tests/index.test.tsx)

And got the same results:

![image](https://user-images.githubusercontent.com/284515/77242570-93837880-6bde-11ea-9535-f15c900ad945.png)

## Things to check

Make sure you [have `@types/jest` in your project `devDependencies` or `dependencies`](https://github.com/klzns/sample-ts-react-app/blob/2d9e84e1823f12d3bf1d883430b1ae62ee551f81/package.json#L9).

Let me know if you find what I'm missing here! Thanks

**Comment by embiem** [comment]
You're right, it does work. I'm honestly not 100% sure why it didn't work back when I posted this issue. 

I remember that I tried your approach, which didn't work at the time, then came across the solution using `ts-jest/utils` (https://github.com/kulshekhar/ts-jest/issues/576#issuecomment-458178545), which worked perfectly.

Thanks for taking the time to double-check this!
